version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/node:10.0.0'
    steps:
      - checkout
      - run:
          name: Install
          command: npm i
      - run:
          name: Test
          command: npm run test