/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var pub_health_daily_report_pb = require('./pub_health_daily_report_pb.js');
goog.object.extend(proto, pub_health_daily_report_pb);
goog.exportSymbol('proto.PubHealthDailyReportFormData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PubHealthDailyReportFormData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.PubHealthDailyReportFormData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PubHealthDailyReportFormData.displayName = 'proto.PubHealthDailyReportFormData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PubHealthDailyReportFormData.prototype.toObject = function(opt_includeInstance) {
  return proto.PubHealthDailyReportFormData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PubHealthDailyReportFormData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PubHealthDailyReportFormData.toObject = function(includeInstance, msg) {
  var f, obj = {
    pubHealthDailyReportRequest: (f = msg.getPubHealthDailyReportRequest()) && pub_health_daily_report_pb.PubHealthDailyReportRequest.toObject(includeInstance, f),
    shareable: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PubHealthDailyReportFormData}
 */
proto.PubHealthDailyReportFormData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PubHealthDailyReportFormData;
  return proto.PubHealthDailyReportFormData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PubHealthDailyReportFormData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PubHealthDailyReportFormData}
 */
proto.PubHealthDailyReportFormData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new pub_health_daily_report_pb.PubHealthDailyReportRequest;
      reader.readMessage(value,pub_health_daily_report_pb.PubHealthDailyReportRequest.deserializeBinaryFromReader);
      msg.setPubHealthDailyReportRequest(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShareable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PubHealthDailyReportFormData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PubHealthDailyReportFormData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PubHealthDailyReportFormData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PubHealthDailyReportFormData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPubHealthDailyReportRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      pub_health_daily_report_pb.PubHealthDailyReportRequest.serializeBinaryToWriter
    );
  }
  f = message.getShareable();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional health.centiva.api.PubHealthDailyReportRequest pub_health_daily_report_request = 1;
 * @return {?proto.health.centiva.api.PubHealthDailyReportRequest}
 */
proto.PubHealthDailyReportFormData.prototype.getPubHealthDailyReportRequest = function() {
  return /** @type{?proto.health.centiva.api.PubHealthDailyReportRequest} */ (
    jspb.Message.getWrapperField(this, pub_health_daily_report_pb.PubHealthDailyReportRequest, 1));
};


/** @param {?proto.health.centiva.api.PubHealthDailyReportRequest|undefined} value */
proto.PubHealthDailyReportFormData.prototype.setPubHealthDailyReportRequest = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.PubHealthDailyReportFormData.prototype.clearPubHealthDailyReportRequest = function() {
  this.setPubHealthDailyReportRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PubHealthDailyReportFormData.prototype.hasPubHealthDailyReportRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool shareable = 2;
 * @return {boolean}
 */
proto.PubHealthDailyReportFormData.prototype.getShareable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.PubHealthDailyReportFormData.prototype.setShareable = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


goog.object.extend(exports, proto);
