/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.hit_foundation.pub_health.PubHealthStatusData', null, global);
goog.exportSymbol('proto.hit_foundation.pub_health.PubHealthStatusData.PubHealthStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hit_foundation.pub_health.PubHealthStatusData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hit_foundation.pub_health.PubHealthStatusData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hit_foundation.pub_health.PubHealthStatusData.displayName = 'proto.hit_foundation.pub_health.PubHealthStatusData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.toObject = function(opt_includeInstance) {
  return proto.hit_foundation.pub_health.PubHealthStatusData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hit_foundation.pub_health.PubHealthStatusData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.pub_health.PubHealthStatusData.toObject = function(includeInstance, msg) {
  var f, obj = {
    pubHealthStatus: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    diagnosisDate: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    shareable: (f = jspb.Message.getBooleanField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hit_foundation.pub_health.PubHealthStatusData}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hit_foundation.pub_health.PubHealthStatusData;
  return proto.hit_foundation.pub_health.PubHealthStatusData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hit_foundation.pub_health.PubHealthStatusData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hit_foundation.pub_health.PubHealthStatusData}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.hit_foundation.pub_health.PubHealthStatusData.PubHealthStatus} */ (reader.readEnum());
      msg.setPubHealthStatus(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDiagnosisDate(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShareable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hit_foundation.pub_health.PubHealthStatusData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hit_foundation.pub_health.PubHealthStatusData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.pub_health.PubHealthStatusData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.hit_foundation.pub_health.PubHealthStatusData.PubHealthStatus} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.PubHealthStatus = {
  NO_STATUS: 0,
  SUSPECTED: 1,
  POSITIVE: 2
};

/**
 * optional PubHealthStatus pub_health_status = 1;
 * @return {!proto.hit_foundation.pub_health.PubHealthStatusData.PubHealthStatus}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.getPubHealthStatus = function() {
  return /** @type {!proto.hit_foundation.pub_health.PubHealthStatusData.PubHealthStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.hit_foundation.pub_health.PubHealthStatusData.PubHealthStatus} value */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.setPubHealthStatus = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.clearPubHealthStatus = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.hasPubHealthStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 diagnosis_date = 2;
 * @return {number}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.getDiagnosisDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.setDiagnosisDate = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.clearDiagnosisDate = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.hasDiagnosisDate = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool shareable = 3;
 * @return {boolean}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.getShareable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.setShareable = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.clearShareable = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.pub_health.PubHealthStatusData.prototype.hasShareable = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.hit_foundation.pub_health);
