/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.health.centiva.api.PubHealthTestReportRequest', null, global);
goog.exportSymbol('proto.health.centiva.api.PubHealthTestReportRequest.Gender', null, global);
goog.exportSymbol('proto.health.centiva.api.PubHealthTestReportResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.health.centiva.api.PubHealthTestReportRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.health.centiva.api.PubHealthTestReportRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.health.centiva.api.PubHealthTestReportRequest.displayName = 'proto.health.centiva.api.PubHealthTestReportRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.health.centiva.api.PubHealthTestReportResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.health.centiva.api.PubHealthTestReportResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.health.centiva.api.PubHealthTestReportResponse.displayName = 'proto.health.centiva.api.PubHealthTestReportResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.health.centiva.api.PubHealthTestReportRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.health.centiva.api.PubHealthTestReportRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.health.centiva.api.PubHealthTestReportRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pubKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    authToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
    signature: jspb.Message.getFieldWithDefault(msg, 3, ""),
    countryCode: jspb.Message.getFieldWithDefault(msg, 4, ""),
    place: jspb.Message.getFieldWithDefault(msg, 5, ""),
    postCode: jspb.Message.getFieldWithDefault(msg, 6, ""),
    verificationCode: jspb.Message.getFieldWithDefault(msg, 7, ""),
    gender: jspb.Message.getFieldWithDefault(msg, 8, 0),
    ageBracket: jspb.Message.getFieldWithDefault(msg, 9, 0),
    bracketSizeYears: jspb.Message.getFieldWithDefault(msg, 10, 0),
    testDate: jspb.Message.getFieldWithDefault(msg, 11, 0),
    resultDate: jspb.Message.getFieldWithDefault(msg, 12, 0),
    outcome: jspb.Message.getBooleanFieldWithDefault(msg, 13, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.health.centiva.api.PubHealthTestReportRequest}
 */
proto.health.centiva.api.PubHealthTestReportRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.health.centiva.api.PubHealthTestReportRequest;
  return proto.health.centiva.api.PubHealthTestReportRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.health.centiva.api.PubHealthTestReportRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.health.centiva.api.PubHealthTestReportRequest}
 */
proto.health.centiva.api.PubHealthTestReportRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPubKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSignature(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountryCode(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlace(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPostCode(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setVerificationCode(value);
      break;
    case 8:
      var value = /** @type {!proto.health.centiva.api.PubHealthTestReportRequest.Gender} */ (reader.readEnum());
      msg.setGender(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAgeBracket(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBracketSizeYears(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTestDate(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setResultDate(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOutcome(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.health.centiva.api.PubHealthTestReportRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.health.centiva.api.PubHealthTestReportRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.health.centiva.api.PubHealthTestReportRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPubKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAuthToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSignature();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCountryCode();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPlace();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPostCode();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getVerificationCode();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getGender();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getAgeBracket();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getBracketSizeYears();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getTestDate();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getResultDate();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getOutcome();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.health.centiva.api.PubHealthTestReportRequest.Gender = {
  GENDER_UNSPECIFIED: 0,
  GENDER_MALE: 1,
  GENDER_FEMALE: 2,
  GENDER_OTHER: 3
};

/**
 * optional string pub_key = 1;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getPubKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setPubKey = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string auth_token = 2;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getAuthToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setAuthToken = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string signature = 3;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getSignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setSignature = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string country_code = 4;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getCountryCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setCountryCode = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string place = 5;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getPlace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setPlace = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string post_code = 6;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getPostCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setPostCode = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string verification_code = 7;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getVerificationCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setVerificationCode = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional Gender gender = 8;
 * @return {!proto.health.centiva.api.PubHealthTestReportRequest.Gender}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getGender = function() {
  return /** @type {!proto.health.centiva.api.PubHealthTestReportRequest.Gender} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {!proto.health.centiva.api.PubHealthTestReportRequest.Gender} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setGender = function(value) {
  jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional int32 age_bracket = 9;
 * @return {number}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getAgeBracket = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setAgeBracket = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 bracket_size_years = 10;
 * @return {number}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getBracketSizeYears = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setBracketSizeYears = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int64 test_date = 11;
 * @return {number}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getTestDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setTestDate = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int64 result_date = 12;
 * @return {number}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getResultDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {number} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setResultDate = function(value) {
  jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional bool outcome = 13;
 * @return {boolean}
 */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.getOutcome = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/** @param {boolean} value */
proto.health.centiva.api.PubHealthTestReportRequest.prototype.setOutcome = function(value) {
  jspb.Message.setProto3BooleanField(this, 13, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.health.centiva.api.PubHealthTestReportResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.health.centiva.api.PubHealthTestReportResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.health.centiva.api.PubHealthTestReportResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.health.centiva.api.PubHealthTestReportResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    ok: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    error: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.health.centiva.api.PubHealthTestReportResponse}
 */
proto.health.centiva.api.PubHealthTestReportResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.health.centiva.api.PubHealthTestReportResponse;
  return proto.health.centiva.api.PubHealthTestReportResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.health.centiva.api.PubHealthTestReportResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.health.centiva.api.PubHealthTestReportResponse}
 */
proto.health.centiva.api.PubHealthTestReportResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOk(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.health.centiva.api.PubHealthTestReportResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.health.centiva.api.PubHealthTestReportResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.health.centiva.api.PubHealthTestReportResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.health.centiva.api.PubHealthTestReportResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOk();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool ok = 1;
 * @return {boolean}
 */
proto.health.centiva.api.PubHealthTestReportResponse.prototype.getOk = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.health.centiva.api.PubHealthTestReportResponse.prototype.setOk = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string error = 2;
 * @return {string}
 */
proto.health.centiva.api.PubHealthTestReportResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.health.centiva.api.PubHealthTestReportResponse.prototype.setError = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.health.centiva.api);
