/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.hit_foundation.query.Query', null, global);
goog.exportSymbol('proto.hit_foundation.query.Query.Gender', null, global);
goog.exportSymbol('proto.hit_foundation.query.Query.OfferQuery', null, global);
goog.exportSymbol('proto.hit_foundation.query.Query.Operation', null, global);
goog.exportSymbol('proto.hit_foundation.query.Query.PUB_HEALTH_STATUS', null, global);
goog.exportSymbol('proto.hit_foundation.query.Query.PhysicalActivityLevel', null, global);
goog.exportSymbol('proto.hit_foundation.query.Query.SmokerStatus', null, global);
goog.exportSymbol('proto.hit_foundation.query.Query.Type', null, global);
goog.exportSymbol('proto.hit_foundation.query.QueryResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hit_foundation.query.Query = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, proto.hit_foundation.query.Query.repeatedFields_, null);
};
goog.inherits(proto.hit_foundation.query.Query, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hit_foundation.query.Query.displayName = 'proto.hit_foundation.query.Query';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hit_foundation.query.Query.OfferQuery = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.hit_foundation.query.Query.OfferQuery.repeatedFields_, null);
};
goog.inherits(proto.hit_foundation.query.Query.OfferQuery, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hit_foundation.query.Query.OfferQuery.displayName = 'proto.hit_foundation.query.Query.OfferQuery';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.hit_foundation.query.QueryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.hit_foundation.query.QueryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.hit_foundation.query.QueryResponse.displayName = 'proto.hit_foundation.query.QueryResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.hit_foundation.query.Query.repeatedFields_ = [7,33];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hit_foundation.query.Query.prototype.toObject = function(opt_includeInstance) {
  return proto.hit_foundation.query.Query.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hit_foundation.query.Query} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.query.Query.toObject = function(includeInstance, msg) {
  var f, obj = {
    queryType: (f = jspb.Message.getField(msg, 26)) == null ? undefined : f,
    op: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    seekerName: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    queryId: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    expirationDate: (f = msg.getExpirationDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    queryUrl: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    incentiveTokenAmountMicros: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    sequenceNumber: (f = jspb.Message.getField(msg, 501)) == null ? undefined : f,
    seekerSignature: msg.getSeekerSignature_asB64(),
    countryCodeList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    minAgeYears: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    maxAgeYears: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    gender: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
    minHeightCm: (f = jspb.Message.getField(msg, 14)) == null ? undefined : f,
    maxHeightCm: (f = jspb.Message.getField(msg, 15)) == null ? undefined : f,
    minWeightKg: (f = jspb.Message.getField(msg, 16)) == null ? undefined : f,
    maxWeightKg: (f = jspb.Message.getField(msg, 17)) == null ? undefined : f,
    minPhysicalActivityLevel: (f = jspb.Message.getField(msg, 18)) == null ? undefined : f,
    maxPhysicalActivityLevel: (f = jspb.Message.getField(msg, 19)) == null ? undefined : f,
    minSmokerStatus: (f = jspb.Message.getField(msg, 20)) == null ? undefined : f,
    maxSmokerStatus: (f = jspb.Message.getField(msg, 21)) == null ? undefined : f,
    queryTitle: (f = jspb.Message.getField(msg, 22)) == null ? undefined : f,
    queryDescription: (f = jspb.Message.getField(msg, 23)) == null ? undefined : f,
    estimatedCompletionTimeSec: (f = jspb.Message.getField(msg, 24)) == null ? undefined : f,
    languageCode: (f = jspb.Message.getField(msg, 25)) == null ? undefined : f,
    offerQuery: (f = msg.getOfferQuery()) && proto.hit_foundation.query.Query.OfferQuery.toObject(includeInstance, f),
    providerPublicKey: (f = jspb.Message.getField(msg, 28)) == null ? undefined : f,
    restrictByRegisteredProvider: (f = jspb.Message.getBooleanField(msg, 29)) == null ? undefined : f,
    diagnosisCodeList: (f = jspb.Message.getRepeatedField(msg, 33)) == null ? undefined : f,
    pubHealthStatus: (f = jspb.Message.getField(msg, 30)) == null ? undefined : f,
    mustCompleteQueryId: (f = jspb.Message.getField(msg, 31)) == null ? undefined : f,
    reactivateAfterMinutes: (f = jspb.Message.getField(msg, 32)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hit_foundation.query.Query}
 */
proto.hit_foundation.query.Query.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hit_foundation.query.Query;
  return proto.hit_foundation.query.Query.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hit_foundation.query.Query} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hit_foundation.query.Query}
 */
proto.hit_foundation.query.Query.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 26:
      var value = /** @type {!proto.hit_foundation.query.Query.Type} */ (reader.readEnum());
      msg.setQueryType(value);
      break;
    case 1:
      var value = /** @type {!proto.hit_foundation.query.Query.Operation} */ (reader.readEnum());
      msg.setOp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSeekerName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQueryId(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpirationDate(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setQueryUrl(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIncentiveTokenAmountMicros(value);
      break;
    case 501:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSequenceNumber(value);
      break;
    case 502:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSeekerSignature(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addCountryCode(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinAgeYears(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxAgeYears(value);
      break;
    case 10:
      var value = /** @type {!proto.hit_foundation.query.Query.Gender} */ (reader.readEnum());
      msg.setGender(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinHeightCm(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxHeightCm(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinWeightKg(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxWeightKg(value);
      break;
    case 18:
      var value = /** @type {!proto.hit_foundation.query.Query.PhysicalActivityLevel} */ (reader.readEnum());
      msg.setMinPhysicalActivityLevel(value);
      break;
    case 19:
      var value = /** @type {!proto.hit_foundation.query.Query.PhysicalActivityLevel} */ (reader.readEnum());
      msg.setMaxPhysicalActivityLevel(value);
      break;
    case 20:
      var value = /** @type {!proto.hit_foundation.query.Query.SmokerStatus} */ (reader.readEnum());
      msg.setMinSmokerStatus(value);
      break;
    case 21:
      var value = /** @type {!proto.hit_foundation.query.Query.SmokerStatus} */ (reader.readEnum());
      msg.setMaxSmokerStatus(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setQueryTitle(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setQueryDescription(value);
      break;
    case 24:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEstimatedCompletionTimeSec(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    case 27:
      var value = new proto.hit_foundation.query.Query.OfferQuery;
      reader.readMessage(value,proto.hit_foundation.query.Query.OfferQuery.deserializeBinaryFromReader);
      msg.setOfferQuery(value);
      break;
    case 28:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderPublicKey(value);
      break;
    case 29:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRestrictByRegisteredProvider(value);
      break;
    case 33:
      var value = /** @type {string} */ (reader.readString());
      msg.addDiagnosisCode(value);
      break;
    case 30:
      var value = /** @type {!proto.hit_foundation.query.Query.PUB_HEALTH_STATUS} */ (reader.readEnum());
      msg.setPubHealthStatus(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMustCompleteQueryId(value);
      break;
    case 32:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReactivateAfterMinutes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hit_foundation.query.Query.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hit_foundation.query.Query.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hit_foundation.query.Query} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.query.Query.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.hit_foundation.query.Query.Type} */ (jspb.Message.getField(message, 26));
  if (f != null) {
    writer.writeEnum(
      26,
      f
    );
  }
  f = /** @type {!proto.hit_foundation.query.Query.Operation} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getExpirationDate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 501));
  if (f != null) {
    writer.writeInt32(
      501,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 502));
  if (f != null) {
    writer.writeBytes(
      502,
      f
    );
  }
  f = message.getCountryCodeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = /** @type {!proto.hit_foundation.query.Query.Gender} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeInt32(
      17,
      f
    );
  }
  f = /** @type {!proto.hit_foundation.query.Query.PhysicalActivityLevel} */ (jspb.Message.getField(message, 18));
  if (f != null) {
    writer.writeEnum(
      18,
      f
    );
  }
  f = /** @type {!proto.hit_foundation.query.Query.PhysicalActivityLevel} */ (jspb.Message.getField(message, 19));
  if (f != null) {
    writer.writeEnum(
      19,
      f
    );
  }
  f = /** @type {!proto.hit_foundation.query.Query.SmokerStatus} */ (jspb.Message.getField(message, 20));
  if (f != null) {
    writer.writeEnum(
      20,
      f
    );
  }
  f = /** @type {!proto.hit_foundation.query.Query.SmokerStatus} */ (jspb.Message.getField(message, 21));
  if (f != null) {
    writer.writeEnum(
      21,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 22));
  if (f != null) {
    writer.writeString(
      22,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 23));
  if (f != null) {
    writer.writeString(
      23,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 24));
  if (f != null) {
    writer.writeInt32(
      24,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 25));
  if (f != null) {
    writer.writeString(
      25,
      f
    );
  }
  f = message.getOfferQuery();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      proto.hit_foundation.query.Query.OfferQuery.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 28));
  if (f != null) {
    writer.writeString(
      28,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 29));
  if (f != null) {
    writer.writeBool(
      29,
      f
    );
  }
  f = message.getDiagnosisCodeList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      33,
      f
    );
  }
  f = /** @type {!proto.hit_foundation.query.Query.PUB_HEALTH_STATUS} */ (jspb.Message.getField(message, 30));
  if (f != null) {
    writer.writeEnum(
      30,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 31));
  if (f != null) {
    writer.writeInt32(
      31,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 32));
  if (f != null) {
    writer.writeInt32(
      32,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.hit_foundation.query.Query.Type = {
  QUERY_TYPE_NIL: 0,
  QUERY_INFO_REQUEST: 1,
  QUERY_REFERRAL_BONUS: 2,
  QUERY_REDEMPTION_OFFER: 3,
  QUERY_COMMS: 4,
  QUERY_PUB_HEALTH: 5,
  QUERY_FEATURE_METADATA: 6
};

/**
 * @enum {number}
 */
proto.hit_foundation.query.Query.Operation = {
  QUERY_NIL: 0,
  QUERY_NEW: 1,
  QUERY_UPDATE: 2,
  QUERY_DISABLE: 3
};

/**
 * @enum {number}
 */
proto.hit_foundation.query.Query.Gender = {
  GENDER_NIL: 0,
  GENDER_FEMALE: 1,
  GENDER_MALE: 2,
  GENDER_OTHER: 3
};

/**
 * @enum {number}
 */
proto.hit_foundation.query.Query.PhysicalActivityLevel = {
  PHYSICAL_ACTIVITY_NIL: 0,
  PHYSICAL_ACTIVITY_LOW: 1,
  PHYSICAL_ACTIVITY_OCCASIONAL_LIGHT: 2,
  PHYSICAL_ACTIVITY_REGULAR: 3,
  PHYSICAL_ACTIVITY_HIGH: 4
};

/**
 * @enum {number}
 */
proto.hit_foundation.query.Query.SmokerStatus = {
  SMOKER_STATUS_NIL: 0,
  SMOKER_STATUS_NONSMOKER: 1,
  SMOKER_STATUS_OCCASIONAL: 2,
  SMOKER_STATUS_REGULAR: 3,
  SMOKER_STATUS_HEAVY: 4
};

/**
 * @enum {number}
 */
proto.hit_foundation.query.Query.PUB_HEALTH_STATUS = {
  PUB_HEALTH_NO_STATUS: 0,
  PUB_HEALTH_SUSPECT: 1,
  PUB_HEALTH_DIAGNOSED: 2
};


/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.hit_foundation.query.Query.OfferQuery.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.toObject = function(opt_includeInstance) {
  return proto.hit_foundation.query.Query.OfferQuery.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hit_foundation.query.Query.OfferQuery} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.query.Query.OfferQuery.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenAmountMicros: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    redeemOffer: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    maxRedeemCount: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    redemptionPublicKey: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    fieldNameList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    redeemPopupMessage: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    redemptionUnitLabel: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hit_foundation.query.Query.OfferQuery}
 */
proto.hit_foundation.query.Query.OfferQuery.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hit_foundation.query.Query.OfferQuery;
  return proto.hit_foundation.query.Query.OfferQuery.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hit_foundation.query.Query.OfferQuery} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hit_foundation.query.Query.OfferQuery}
 */
proto.hit_foundation.query.Query.OfferQuery.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTokenAmountMicros(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRedeemOffer(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxRedeemCount(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedemptionPublicKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addFieldName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedeemPopupMessage(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedemptionUnitLabel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hit_foundation.query.Query.OfferQuery.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hit_foundation.query.Query.OfferQuery} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.query.Query.OfferQuery.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFieldNameList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional int64 token_amount_micros = 1;
 * @return {number}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.getTokenAmountMicros = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.OfferQuery.prototype.setTokenAmountMicros = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.clearTokenAmountMicros = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.hasTokenAmountMicros = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 redeem_offer = 2;
 * @return {number}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.getRedeemOffer = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.OfferQuery.prototype.setRedeemOffer = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.clearRedeemOffer = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.hasRedeemOffer = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 max_redeem_count = 3;
 * @return {number}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.getMaxRedeemCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.OfferQuery.prototype.setMaxRedeemCount = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.clearMaxRedeemCount = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.hasMaxRedeemCount = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string redemption_public_key = 4;
 * @return {string}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.getRedemptionPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.OfferQuery.prototype.setRedemptionPublicKey = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.clearRedemptionPublicKey = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.hasRedemptionPublicKey = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated string field_name = 5;
 * @return {!Array<string>}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.getFieldNameList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.hit_foundation.query.Query.OfferQuery.prototype.setFieldNameList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.addFieldName = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.clearFieldNameList = function() {
  this.setFieldNameList([]);
};


/**
 * optional string redeem_popup_message = 6;
 * @return {string}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.getRedeemPopupMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.OfferQuery.prototype.setRedeemPopupMessage = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.clearRedeemPopupMessage = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.hasRedeemPopupMessage = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string redemption_unit_label = 7;
 * @return {string}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.getRedemptionUnitLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.OfferQuery.prototype.setRedemptionUnitLabel = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.clearRedemptionUnitLabel = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.OfferQuery.prototype.hasRedemptionUnitLabel = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Type query_type = 26;
 * @return {!proto.hit_foundation.query.Query.Type}
 */
proto.hit_foundation.query.Query.prototype.getQueryType = function() {
  return /** @type {!proto.hit_foundation.query.Query.Type} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/** @param {!proto.hit_foundation.query.Query.Type} value */
proto.hit_foundation.query.Query.prototype.setQueryType = function(value) {
  jspb.Message.setField(this, 26, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearQueryType = function() {
  jspb.Message.setField(this, 26, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasQueryType = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional Operation op = 1;
 * @return {!proto.hit_foundation.query.Query.Operation}
 */
proto.hit_foundation.query.Query.prototype.getOp = function() {
  return /** @type {!proto.hit_foundation.query.Query.Operation} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.hit_foundation.query.Query.Operation} value */
proto.hit_foundation.query.Query.prototype.setOp = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearOp = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasOp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string seeker_name = 2;
 * @return {string}
 */
proto.hit_foundation.query.Query.prototype.getSeekerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.prototype.setSeekerName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearSeekerName = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasSeekerName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 query_id = 3;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getQueryId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setQueryId = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearQueryId = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasQueryId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp expiration_date = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.hit_foundation.query.Query.prototype.getExpirationDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.hit_foundation.query.Query.prototype.setExpirationDate = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearExpirationDate = function() {
  this.setExpirationDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasExpirationDate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string query_url = 5;
 * @return {string}
 */
proto.hit_foundation.query.Query.prototype.getQueryUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.prototype.setQueryUrl = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearQueryUrl = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasQueryUrl = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int32 incentive_token_amount_micros = 6;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getIncentiveTokenAmountMicros = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setIncentiveTokenAmountMicros = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearIncentiveTokenAmountMicros = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasIncentiveTokenAmountMicros = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 sequence_number = 501;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getSequenceNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 501, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setSequenceNumber = function(value) {
  jspb.Message.setField(this, 501, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearSequenceNumber = function() {
  jspb.Message.setField(this, 501, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasSequenceNumber = function() {
  return jspb.Message.getField(this, 501) != null;
};


/**
 * optional bytes seeker_signature = 502;
 * @return {!(string|Uint8Array)}
 */
proto.hit_foundation.query.Query.prototype.getSeekerSignature = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 502, ""));
};


/**
 * optional bytes seeker_signature = 502;
 * This is a type-conversion wrapper around `getSeekerSignature()`
 * @return {string}
 */
proto.hit_foundation.query.Query.prototype.getSeekerSignature_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSeekerSignature()));
};


/**
 * optional bytes seeker_signature = 502;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSeekerSignature()`
 * @return {!Uint8Array}
 */
proto.hit_foundation.query.Query.prototype.getSeekerSignature_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSeekerSignature()));
};


/** @param {!(string|Uint8Array)} value */
proto.hit_foundation.query.Query.prototype.setSeekerSignature = function(value) {
  jspb.Message.setField(this, 502, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearSeekerSignature = function() {
  jspb.Message.setField(this, 502, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasSeekerSignature = function() {
  return jspb.Message.getField(this, 502) != null;
};


/**
 * repeated string country_code = 7;
 * @return {!Array<string>}
 */
proto.hit_foundation.query.Query.prototype.getCountryCodeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<string>} value */
proto.hit_foundation.query.Query.prototype.setCountryCodeList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.hit_foundation.query.Query.prototype.addCountryCode = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.hit_foundation.query.Query.prototype.clearCountryCodeList = function() {
  this.setCountryCodeList([]);
};


/**
 * optional int32 min_age_years = 8;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getMinAgeYears = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setMinAgeYears = function(value) {
  jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMinAgeYears = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMinAgeYears = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional int32 max_age_years = 9;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getMaxAgeYears = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setMaxAgeYears = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMaxAgeYears = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMaxAgeYears = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional Gender gender = 10;
 * @return {!proto.hit_foundation.query.Query.Gender}
 */
proto.hit_foundation.query.Query.prototype.getGender = function() {
  return /** @type {!proto.hit_foundation.query.Query.Gender} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {!proto.hit_foundation.query.Query.Gender} value */
proto.hit_foundation.query.Query.prototype.setGender = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearGender = function() {
  jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasGender = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional int32 min_height_cm = 14;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getMinHeightCm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setMinHeightCm = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMinHeightCm = function() {
  jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMinHeightCm = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional int32 max_height_cm = 15;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getMaxHeightCm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setMaxHeightCm = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMaxHeightCm = function() {
  jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMaxHeightCm = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional int32 min_weight_kg = 16;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getMinWeightKg = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setMinWeightKg = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMinWeightKg = function() {
  jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMinWeightKg = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional int32 max_weight_kg = 17;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getMaxWeightKg = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setMaxWeightKg = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMaxWeightKg = function() {
  jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMaxWeightKg = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional PhysicalActivityLevel min_physical_activity_level = 18;
 * @return {!proto.hit_foundation.query.Query.PhysicalActivityLevel}
 */
proto.hit_foundation.query.Query.prototype.getMinPhysicalActivityLevel = function() {
  return /** @type {!proto.hit_foundation.query.Query.PhysicalActivityLevel} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/** @param {!proto.hit_foundation.query.Query.PhysicalActivityLevel} value */
proto.hit_foundation.query.Query.prototype.setMinPhysicalActivityLevel = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMinPhysicalActivityLevel = function() {
  jspb.Message.setField(this, 18, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMinPhysicalActivityLevel = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional PhysicalActivityLevel max_physical_activity_level = 19;
 * @return {!proto.hit_foundation.query.Query.PhysicalActivityLevel}
 */
proto.hit_foundation.query.Query.prototype.getMaxPhysicalActivityLevel = function() {
  return /** @type {!proto.hit_foundation.query.Query.PhysicalActivityLevel} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/** @param {!proto.hit_foundation.query.Query.PhysicalActivityLevel} value */
proto.hit_foundation.query.Query.prototype.setMaxPhysicalActivityLevel = function(value) {
  jspb.Message.setField(this, 19, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMaxPhysicalActivityLevel = function() {
  jspb.Message.setField(this, 19, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMaxPhysicalActivityLevel = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional SmokerStatus min_smoker_status = 20;
 * @return {!proto.hit_foundation.query.Query.SmokerStatus}
 */
proto.hit_foundation.query.Query.prototype.getMinSmokerStatus = function() {
  return /** @type {!proto.hit_foundation.query.Query.SmokerStatus} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/** @param {!proto.hit_foundation.query.Query.SmokerStatus} value */
proto.hit_foundation.query.Query.prototype.setMinSmokerStatus = function(value) {
  jspb.Message.setField(this, 20, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMinSmokerStatus = function() {
  jspb.Message.setField(this, 20, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMinSmokerStatus = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional SmokerStatus max_smoker_status = 21;
 * @return {!proto.hit_foundation.query.Query.SmokerStatus}
 */
proto.hit_foundation.query.Query.prototype.getMaxSmokerStatus = function() {
  return /** @type {!proto.hit_foundation.query.Query.SmokerStatus} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/** @param {!proto.hit_foundation.query.Query.SmokerStatus} value */
proto.hit_foundation.query.Query.prototype.setMaxSmokerStatus = function(value) {
  jspb.Message.setField(this, 21, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMaxSmokerStatus = function() {
  jspb.Message.setField(this, 21, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMaxSmokerStatus = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional string query_title = 22;
 * @return {string}
 */
proto.hit_foundation.query.Query.prototype.getQueryTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.prototype.setQueryTitle = function(value) {
  jspb.Message.setField(this, 22, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearQueryTitle = function() {
  jspb.Message.setField(this, 22, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasQueryTitle = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional string query_description = 23;
 * @return {string}
 */
proto.hit_foundation.query.Query.prototype.getQueryDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.prototype.setQueryDescription = function(value) {
  jspb.Message.setField(this, 23, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearQueryDescription = function() {
  jspb.Message.setField(this, 23, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasQueryDescription = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional int32 estimated_completion_time_sec = 24;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getEstimatedCompletionTimeSec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 24, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setEstimatedCompletionTimeSec = function(value) {
  jspb.Message.setField(this, 24, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearEstimatedCompletionTimeSec = function() {
  jspb.Message.setField(this, 24, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasEstimatedCompletionTimeSec = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional string language_code = 25;
 * @return {string}
 */
proto.hit_foundation.query.Query.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.prototype.setLanguageCode = function(value) {
  jspb.Message.setField(this, 25, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearLanguageCode = function() {
  jspb.Message.setField(this, 25, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasLanguageCode = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional OfferQuery offer_query = 27;
 * @return {?proto.hit_foundation.query.Query.OfferQuery}
 */
proto.hit_foundation.query.Query.prototype.getOfferQuery = function() {
  return /** @type{?proto.hit_foundation.query.Query.OfferQuery} */ (
    jspb.Message.getWrapperField(this, proto.hit_foundation.query.Query.OfferQuery, 27));
};


/** @param {?proto.hit_foundation.query.Query.OfferQuery|undefined} value */
proto.hit_foundation.query.Query.prototype.setOfferQuery = function(value) {
  jspb.Message.setWrapperField(this, 27, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearOfferQuery = function() {
  this.setOfferQuery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasOfferQuery = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional string provider_public_key = 28;
 * @return {string}
 */
proto.hit_foundation.query.Query.prototype.getProviderPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 28, ""));
};


/** @param {string} value */
proto.hit_foundation.query.Query.prototype.setProviderPublicKey = function(value) {
  jspb.Message.setField(this, 28, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearProviderPublicKey = function() {
  jspb.Message.setField(this, 28, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasProviderPublicKey = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional bool restrict_by_registered_provider = 29;
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.getRestrictByRegisteredProvider = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 29, false));
};


/** @param {boolean} value */
proto.hit_foundation.query.Query.prototype.setRestrictByRegisteredProvider = function(value) {
  jspb.Message.setField(this, 29, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearRestrictByRegisteredProvider = function() {
  jspb.Message.setField(this, 29, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasRestrictByRegisteredProvider = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * repeated string diagnosis_code = 33;
 * @return {!Array<string>}
 */
proto.hit_foundation.query.Query.prototype.getDiagnosisCodeList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 33));
};


/** @param {!Array<string>} value */
proto.hit_foundation.query.Query.prototype.setDiagnosisCodeList = function(value) {
  jspb.Message.setField(this, 33, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.hit_foundation.query.Query.prototype.addDiagnosisCode = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 33, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.hit_foundation.query.Query.prototype.clearDiagnosisCodeList = function() {
  this.setDiagnosisCodeList([]);
};


/**
 * optional PUB_HEALTH_STATUS pub_health_status = 30;
 * @return {!proto.hit_foundation.query.Query.PUB_HEALTH_STATUS}
 */
proto.hit_foundation.query.Query.prototype.getPubHealthStatus = function() {
  return /** @type {!proto.hit_foundation.query.Query.PUB_HEALTH_STATUS} */ (jspb.Message.getFieldWithDefault(this, 30, 0));
};


/** @param {!proto.hit_foundation.query.Query.PUB_HEALTH_STATUS} value */
proto.hit_foundation.query.Query.prototype.setPubHealthStatus = function(value) {
  jspb.Message.setField(this, 30, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearPubHealthStatus = function() {
  jspb.Message.setField(this, 30, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasPubHealthStatus = function() {
  return jspb.Message.getField(this, 30) != null;
};


/**
 * optional int32 must_complete_query_id = 31;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getMustCompleteQueryId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setMustCompleteQueryId = function(value) {
  jspb.Message.setField(this, 31, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearMustCompleteQueryId = function() {
  jspb.Message.setField(this, 31, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasMustCompleteQueryId = function() {
  return jspb.Message.getField(this, 31) != null;
};


/**
 * optional int32 reactivate_after_minutes = 32;
 * @return {number}
 */
proto.hit_foundation.query.Query.prototype.getReactivateAfterMinutes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 32, 0));
};


/** @param {number} value */
proto.hit_foundation.query.Query.prototype.setReactivateAfterMinutes = function(value) {
  jspb.Message.setField(this, 32, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.Query.prototype.clearReactivateAfterMinutes = function() {
  jspb.Message.setField(this, 32, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.Query.prototype.hasReactivateAfterMinutes = function() {
  return jspb.Message.getField(this, 32) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.hit_foundation.query.QueryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.hit_foundation.query.QueryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.hit_foundation.query.QueryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.query.QueryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    queryId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    status: (f = jspb.Message.getBooleanField(msg, 3)) == null ? undefined : f,
    message: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.hit_foundation.query.QueryResponse}
 */
proto.hit_foundation.query.QueryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.hit_foundation.query.QueryResponse;
  return proto.hit_foundation.query.QueryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.hit_foundation.query.QueryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.hit_foundation.query.QueryResponse}
 */
proto.hit_foundation.query.QueryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQueryId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.hit_foundation.query.QueryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.hit_foundation.query.QueryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.hit_foundation.query.QueryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.hit_foundation.query.QueryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional int32 query_id = 1;
 * @return {number}
 */
proto.hit_foundation.query.QueryResponse.prototype.getQueryId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.hit_foundation.query.QueryResponse.prototype.setQueryId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.QueryResponse.prototype.clearQueryId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.QueryResponse.prototype.hasQueryId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp timestamp = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.hit_foundation.query.QueryResponse.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.hit_foundation.query.QueryResponse.prototype.setTimestamp = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.hit_foundation.query.QueryResponse.prototype.clearTimestamp = function() {
  this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.QueryResponse.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool status = 3;
 * @return {boolean}
 */
proto.hit_foundation.query.QueryResponse.prototype.getStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.hit_foundation.query.QueryResponse.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.QueryResponse.prototype.clearStatus = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.QueryResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string message = 4;
 * @return {string}
 */
proto.hit_foundation.query.QueryResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.hit_foundation.query.QueryResponse.prototype.setMessage = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 */
proto.hit_foundation.query.QueryResponse.prototype.clearMessage = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.hit_foundation.query.QueryResponse.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.hit_foundation.query);
